"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app

    https://www.youtube.com/watch?v=DVOoHL2Bp_o
    http://www.marinamele.com/from-a-python-script-to-a-portable-mac-application-with-py2app

"""

from setuptools import setup

APP = ['scoremaster.py']
"""DATA_FILES = ['/images/1mile.png', '/images/2mile.png', '/images/impactxs.png', '/images/impactxs_ico.jpg', '/events/20220901_1m_event.json', '/events/20220901_2m_event.json', '/events/20220901_1m_event-original.json', '/events/20220901_2m_event-original.json', 'new_1mile.json', 'new_2mile.json']"""
DATA_FILES = []
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)